name: MSYS2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        sys:
          - mingw64
          - mingw32
          - clang64
          - clang32

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: base-devel
        pacboy: toolchain:p cmake:p SDL2:p SDL2_image:p SDL2_mixer:p expat:p glew:p

    - uses: actions/checkout@v3

    - name: Configure
      shell: msys2 {0}
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: msys2 {0}
      run: cmake --build build --config ${{env.BUILD_TYPE}}
